# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: ***REMOVED***
  password: ***REMOVED***
  host: ***REMOVED***
  port: 5432
  database: ***REMOVED***

development:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: ***REMOVED***
  password: ***REMOVED***
  host: ***REMOVED***
  port: 5432
  database: ***REMOVED***

production:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: ***REMOVED***
  password: ***REMOVED***
  host: ***REMOVED***
  port: 5432
  database: ***REMOVED***